// Code generated by goctl. DO NOT EDIT!
// Source: app.proto

package server

import (
	"context"

	"mtzero/src/app/app"
	"mtzero/src/app/internal/logic"
	"mtzero/src/app/internal/svc"
)

type AppServer struct {
	svcCtx *svc.ServiceContext
}

func NewAppServer(svcCtx *svc.ServiceContext) *AppServer {
	return &AppServer{
		svcCtx: svcCtx,
	}
}

func (s *AppServer) GetAppInfo(ctx context.Context, in *app.GetAppInfoReq) (*app.GetAppInfoResp, error) {
	l := logic.NewGetAppInfoLogic(ctx, s.svcCtx)
	return l.GetAppInfo(in)
}
