// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

package app

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UpdateType int32

const (
	UpdateType_None  UpdateType = 0
	UpdateType_Soft  UpdateType = 1
	UpdateType_Force UpdateType = 2
)

var UpdateType_name = map[int32]string{
	0: "None",
	1: "Soft",
	2: "Force",
}

var UpdateType_value = map[string]int32{
	"None":  0,
	"Soft":  1,
	"Force": 2,
}

func (x UpdateType) String() string {
	return proto.EnumName(UpdateType_name, int32(x))
}

func (UpdateType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

type GetAppInfoReq struct {
	Platform             string   `protobuf:"bytes,1,opt,name=platform,proto3" json:"platform,omitempty"`
	Version              string   `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAppInfoReq) Reset()         { *m = GetAppInfoReq{} }
func (m *GetAppInfoReq) String() string { return proto.CompactTextString(m) }
func (*GetAppInfoReq) ProtoMessage()    {}
func (*GetAppInfoReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{0}
}

func (m *GetAppInfoReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppInfoReq.Unmarshal(m, b)
}
func (m *GetAppInfoReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppInfoReq.Marshal(b, m, deterministic)
}
func (m *GetAppInfoReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppInfoReq.Merge(m, src)
}
func (m *GetAppInfoReq) XXX_Size() int {
	return xxx_messageInfo_GetAppInfoReq.Size(m)
}
func (m *GetAppInfoReq) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppInfoReq.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppInfoReq proto.InternalMessageInfo

func (m *GetAppInfoReq) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *GetAppInfoReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type GetAppInfoResp struct {
	Version              string     `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	Desc                 string     `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	Url                  string     `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Type                 UpdateType `protobuf:"varint,4,opt,name=type,proto3,enum=app.UpdateType" json:"type,omitempty"`
	Env                  string     `protobuf:"bytes,5,opt,name=env,proto3" json:"env,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *GetAppInfoResp) Reset()         { *m = GetAppInfoResp{} }
func (m *GetAppInfoResp) String() string { return proto.CompactTextString(m) }
func (*GetAppInfoResp) ProtoMessage()    {}
func (*GetAppInfoResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_e0f9056a14b86d47, []int{1}
}

func (m *GetAppInfoResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAppInfoResp.Unmarshal(m, b)
}
func (m *GetAppInfoResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAppInfoResp.Marshal(b, m, deterministic)
}
func (m *GetAppInfoResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAppInfoResp.Merge(m, src)
}
func (m *GetAppInfoResp) XXX_Size() int {
	return xxx_messageInfo_GetAppInfoResp.Size(m)
}
func (m *GetAppInfoResp) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAppInfoResp.DiscardUnknown(m)
}

var xxx_messageInfo_GetAppInfoResp proto.InternalMessageInfo

func (m *GetAppInfoResp) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *GetAppInfoResp) GetDesc() string {
	if m != nil {
		return m.Desc
	}
	return ""
}

func (m *GetAppInfoResp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *GetAppInfoResp) GetType() UpdateType {
	if m != nil {
		return m.Type
	}
	return UpdateType_None
}

func (m *GetAppInfoResp) GetEnv() string {
	if m != nil {
		return m.Env
	}
	return ""
}

func init() {
	proto.RegisterEnum("app.UpdateType", UpdateType_name, UpdateType_value)
	proto.RegisterType((*GetAppInfoReq)(nil), "app.GetAppInfoReq")
	proto.RegisterType((*GetAppInfoResp)(nil), "app.GetAppInfoResp")
}

func init() { proto.RegisterFile("app.proto", fileDescriptor_e0f9056a14b86d47) }

var fileDescriptor_e0f9056a14b86d47 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x50, 0x4d, 0x4b, 0x43, 0x31,
	0x10, 0x34, 0x7d, 0xa9, 0xf6, 0x2d, 0x58, 0xc3, 0x7a, 0x09, 0x3d, 0x95, 0x7a, 0x29, 0x0a, 0x3d,
	0x54, 0xbc, 0x79, 0xe9, 0x41, 0xc5, 0x8b, 0x87, 0xa7, 0xfe, 0x80, 0xd8, 0xee, 0x03, 0xa1, 0x66,
	0xd7, 0x24, 0x3e, 0xe8, 0x2f, 0xf0, 0x6f, 0x4b, 0xe2, 0x47, 0x5b, 0xbc, 0xcd, 0xee, 0xce, 0xcc,
	0x0e, 0x03, 0xb5, 0x13, 0x99, 0x49, 0xe0, 0xc4, 0x58, 0x39, 0x91, 0xc9, 0x0d, 0x1c, 0xdf, 0x51,
	0x5a, 0x88, 0xdc, 0xfb, 0x96, 0x1b, 0x7a, 0xc7, 0x11, 0x0c, 0x64, 0xed, 0x52, 0xcb, 0xe1, 0xcd,
	0xaa, 0xb1, 0x9a, 0xd6, 0xcd, 0xdf, 0x8c, 0x16, 0x8e, 0x3a, 0x0a, 0xf1, 0x95, 0xbd, 0xed, 0x95,
	0xd3, 0xef, 0x38, 0xf9, 0x54, 0x30, 0xdc, 0xf5, 0x89, 0xb2, 0x4b, 0x56, 0x7b, 0x64, 0x44, 0xd0,
	0x2b, 0x8a, 0xcb, 0x1f, 0x8f, 0x82, 0xd1, 0x40, 0xf5, 0x11, 0xd6, 0xb6, 0x2a, 0xab, 0x0c, 0xf1,
	0x0c, 0x74, 0xda, 0x08, 0x59, 0x3d, 0x56, 0xd3, 0xe1, 0xfc, 0x64, 0x96, 0x83, 0x3f, 0xcb, 0xca,
	0x25, 0x7a, 0xda, 0x08, 0x35, 0xe5, 0x98, 0x65, 0xe4, 0x3b, 0xdb, 0xff, 0x96, 0x91, 0xef, 0xce,
	0x2f, 0x00, 0xb6, 0x2c, 0x1c, 0x80, 0x7e, 0x60, 0x4f, 0xe6, 0x20, 0xa3, 0x47, 0x6e, 0x93, 0x51,
	0x58, 0x43, 0xff, 0x96, 0xc3, 0x92, 0x4c, 0x6f, 0x7e, 0x0d, 0xd5, 0x42, 0x04, 0xaf, 0x00, 0xb6,
	0xe1, 0x11, 0xcb, 0xab, 0xbd, 0x56, 0x46, 0xa7, 0xff, 0x76, 0x51, 0x5e, 0x0e, 0x4b, 0x8f, 0x97,
	0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xab, 0x70, 0x44, 0xfb, 0x54, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// AppClient is the client API for App service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppClient interface {
	GetAppInfo(ctx context.Context, in *GetAppInfoReq, opts ...grpc.CallOption) (*GetAppInfoResp, error)
}

type appClient struct {
	cc grpc.ClientConnInterface
}

func NewAppClient(cc grpc.ClientConnInterface) AppClient {
	return &appClient{cc}
}

func (c *appClient) GetAppInfo(ctx context.Context, in *GetAppInfoReq, opts ...grpc.CallOption) (*GetAppInfoResp, error) {
	out := new(GetAppInfoResp)
	err := c.cc.Invoke(ctx, "/app.App/GetAppInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AppServer is the server API for App service.
type AppServer interface {
	GetAppInfo(context.Context, *GetAppInfoReq) (*GetAppInfoResp, error)
}

// UnimplementedAppServer can be embedded to have forward compatible implementations.
type UnimplementedAppServer struct {
}

func (*UnimplementedAppServer) GetAppInfo(ctx context.Context, req *GetAppInfoReq) (*GetAppInfoResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAppInfo not implemented")
}

func RegisterAppServer(s *grpc.Server, srv AppServer) {
	s.RegisterService(&_App_serviceDesc, srv)
}

func _App_GetAppInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AppServer).GetAppInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app.App/GetAppInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AppServer).GetAppInfo(ctx, req.(*GetAppInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _App_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app.App",
	HandlerType: (*AppServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppInfo",
			Handler:    _App_GetAppInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}
