// Code generated by goctl. DO NOT EDIT.
package types

type AppReq struct {
}

type AppResp struct {
	Version string `json:"version"`
	Desc    string `json:"desc"`
	Url     string `json:"url"`
	Type    int8   `json:"type,options=0|1|2"` // 0:不更新，1:软更，2:强更
}
